### ISSUE TITLE
Calculate the summary statistics for all the schedules

### ISSUE THREAD

**Issue by aammd** [aammd/precipitation.experiment.schedule#1]
We need to calculate some numbers that summarize the variation in rainfall in the experiments.  Please reply to this issue with your thoughts and we will make a list of what needs to be done

**Comment by nacmarino** [comment]
We can use the script we worked on...I already uploaded it to my GitHub repository, together with a script to calculate some summary statistics from the water depth measurements. We can base our work from there, maybe...

**Comment by farjalla** [comment]
That's a very good point. Some first thoughts:
1. Total number of days without water
2. Number of days with water BEFORE final sampling
3. Number of dry periods (how many times during the experiment the bromeliad dried up)
4. Temporal variation in the water level (a coefficient of variation)

**Comment by aammd** [comment]
Sounds good! @nacmarino why don't you copy your script file over into the `/site_comparisons` folder in this repository ([here's a link](https://github.com/aammd/precipitation.experiment.schedule/tree/master/site_comparison)) then we can all hack away

**Comment by aammd** [comment]
> 1. Number of days with water BEFORE final sampling

@farjalla could you clarify this one?

**Comment by nacmarino** [comment]
How do I do it?

**Comment by farjalla** [comment]
Number of days with water BEFORE final sampling.
Remember we had to add water before the final sampling (a rain event in the last days)? Some bromeliads might already have water in their tanks before this common rain event but others not. Thus, despite having water in all bromeliads to final sample, the last colonization/succession period for aquatic organisms may vary among plants.

**Comment by aammd** [comment]
I think we will be continuing this discussion over at Srivastavalab/bwgtools#6
